# Generated by Django 4.2.5 on 2023-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_comment_date_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tarih - Saat'),
        ),
    ]
