# Generated by Django 4.2.5 on 2023-09-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_alter_comment_date_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Alt Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('Price', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Fiyat')),
                ('image', models.FileField(upload_to='Cards', verbose_name='Resim')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMy.category', verbose_name='Kategori')),
            ],
        ),
    ]
