# Generated by Django 4.2.5 on 2023-10-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
